### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by nature1996** [Ugre101/TEoG_Unity_2#1]
I would have some suggestion to help with the project.

First and foremost, I would recommend you to branch your project into a Dev branch for a working unreleased version, and keep the latest released version in the master branch. I would also recommend you to create a new branch for wip features so that it will be easier to revert/give up a branch, as the working version will be safe. You can merge them when the feature is done. That will also help those who would like to work on their own extension, features or bug-fix, or even just help the development.

 Second, I would recommend you to add .meta file to your .gitignore.

I believe this project has a lot of potential, can't wait to see where this new direction will lead.

**Comment by Ugre101** [comment]
Not sure if I can ignore .meta as I already have issues with references going missing sometimes, especially for enemies on map.

I shall try to split the branches going forward, it might take some time to fully realise as I don't have much experience working that way.
